### ISSUE TITLE
Typescript error with its new version

### ISSUE THREAD

**Issue by markmssd** [bharatraj88/angular2-tooltip#10]
```
ERROR in ./~/angular2-tooltip/src/content/options.d.ts
Module build failed: Error: Debug Failure. False expression: Output generation failed
    at Object.assert (/Users/xxx/dev/yyy/node_modules/typescript/lib/typescript.js:2437:23)
    at Object.transpileModule (/Users/xxx/dev/yyy/node_modules/typescript/lib/typescript.js:54677:18)
    at TypeScriptFileRefactor.transpile (/Users/x/dev/yyy/node_modules/@ngtools/webpack/src/refactor.js:165:25)
    at /Users/xxx/dev/yyy/node_modules/@ngtools/webpack/src/loader.js:151:37
 @ ./~/angular2-tooltip/src/tooltip.ts 13:0-45
 @ ./~/angular2-tooltip/src/tool-tip.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main
```

angular2-tooltip v2.2.1 with angular v2.4.0 and typescript v2.0.6

**Comment by bharatraj88** [comment]
Please upgrade to 2.3.0. This issue has been addressed.

**Comment by markmssd** [comment]
It works, thanks a lot!
