### ISSUE TITLE
Library packaging issue

### ISSUE THREAD

**Issue by joshstallnick** [bharatraj88/angular2-tooltip#24]
When importing module after installing I get the following error. I have tried many work arounds to no avail. I will have to look for a different option.

potential fix/best practice: https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325

`./node_modules/angular2-tooltip/index.ts`
Module build failed: Error: C:\Users\main\IdeaProjects\angular-practice\angular-project\node_modules\angular2-tooltip\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\main\IdeaProjects\angular-practice\angular-project\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:656:23)
    at plugin.done.then (C:\Users\main\IdeaProjects\angular-practice\angular-project\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 44:25-52
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts`

**Comment by crjavier** [comment]
so is it not fixed yet? i'm having problems with that same issue too
