### ISSUE TITLE
Can't import the module

### ISSUE THREAD

**Issue by Adambs** [bharatraj88/angular2-tooltip#26]
ERROR in ./node_modules/angular2-tooltip/index.ts
Module build failed: Error: C:\Users\Adam\Desktop\ShiftsCraft\Front\node_modules\angular2-tooltip\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Adam\Desktop\ShiftsCraft\Front\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\Users\Adam\Desktop\ShiftsCraft\Front\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by lucypoly** [comment]
+1

**Comment by eladco898** [comment]
+1

**Comment by polaroi8d** [comment]
Any updated from the author?
